### ISSUE TITLE
Referencing the alpha versions has caused code to break

### ISSUE THREAD

**Issue by StingyJack** [WildGums/CsvTextEditor#552]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ x] WPF
 - [ ] UWP
 - [ ] iOS
 - [ ] Android
 - [ ] .NET Standard
 - [ ] .NET Core

## Component

What component is this issue occurring in?

## Version of Library
unversioned source code

## Version of OS(s) listed above with issue
Any/all

## Steps to Reproduce
1. git clone
2.  open solution
3. build solution

## Expected Behavior
It compiles

## Actual Behavior

It fails with errors

Some of the Orc packages reference pre-release versions of Cattel MVVM.  Those prerelease versions changed the accessibility on CommandContainerBase and that means the handful of classes that inherit from that class are now broken and the project doesn't compile. Forcing the use of a stable release of Cattel.MVVM, fixes this, and I can run the program but unfortunately it does nothing useful.  I cant even type a comma in!  

It would be nice if the current state of the project were clear in the readme. It gives the impression of a usable program that I just wasted an hour trying to get to work to find out its incomplete.

**Comment by GeertvanHorrik** [comment]
You probably used the _develop_ branch, which is the active development branch. Best is to use the _master_ branch which is used for stable releases.

**Comment by StingyJack** [comment]
Well I would have liked to have been able to at least try submit a PR to address #551.  That dev branch is more than 1000 commits ahead of master, and I dont really want to deal with that kind of distance. Thanks for getting back to me about this though.

**Comment by StingyJack** [comment]
FYI - When trying to build the master branch.... I tried commenting out the nuget.config to see if that made a difference, but result was the same.  Looks like someone revoked a cert. 
![image](https://github.com/WildGums/CsvTextEditor/assets/15381181/e402b8aa-23f8-435e-afcf-eee0999c94d0)
